from __future__ import print_function
from craigslist import CraigslistForSale
from datetime import datetime
import json
import re
import time

target_to_class = {
"1":"app", #app: appliances by owner"
"2":"ard", #ard: arts and crafts by dealer"
"3":"art", #art: arts & crafts - by owner"
"4":"atd", #atd: antiques - by dealer"
"5":"atq", #atq: antiques - by owner"
"6":"bab", #bab: baby & kid stuff - by owner"
"7":"bad", #bad: baby & kid stuff - by dealer"
"8":"bar", #bar: barter"
"9":"bdp", #bdp: bicycle parts - by dealer"
"10":"bfd", #bfd: business/commercial - by dealer"
"11":"bfs", #bfs: business/commercial - by owner"
"12":"bid", #bid: bicycles - by dealer"
"13":"bik", #bik: bicycles - by owner"
"14":"bkd", #bkd: books & magazines - by dealer"
"15":"bks", #bks: books & magazines - by owner"
"16":"boa", #boa: boats - by owner"
"17":"bod", #bod: boats - by dealer"
"18":"bop", #bop: bicycle parts - by owner"
"19":"bpo", #bpo: boat parts - by owner"
"20":"cbd", #cbd: collectibles - by dealer"
"21":"cld", #cld: clothing and accessories by dealer"
"22":"clo", #clo: clothing and accessories by owner"
"23":"clt", #clt: collectibles - by owner"
"24":"ctd", #ctd: cars & trucks - by dealer"
"25":"cto", #cto: cars & trucks - by owner"
"26":"eld", #eld: electronics - by dealer"
"27":"ele", #ele: electronics - by owwner"
"28":"emd", #emd: cds / dvds / vhs - by owner"
"29":"emq", #emq: cds / dvds / vhs - by dealer"
"30":"fod", #fod: general for sale - by dealer"
"31":"for", #for: general for sale by owner"
"32":"fuo", #fuo: furniture - by owner"
"33":"grd", #grd: farm & garden - by owner"
"34":"grq", #grq: farm and garden by dealer"
"35":"hab", #hab: health and beauty - by owner"
"36":"had", #had: health and beauty - by dealer"
"37":"hsd", #hsd: household items - by dealer"
"38":"hsh", #hsh: household items - by owner"
"39":"hvd", #hvd: heavy equipment - by dealer"
"40":"hvo", #hvo: heavy equipment - by owner"
"41":"jwd", #jwd: jewelry - by dealer"
"42":"jwl", #jwl: jewelry - by owner"
"43":"mad", #mad: materials - by dealer"
"44":"mat", #mat: materials by owner"
"45":"mcd", #mcd: motorcycles/scooters - by dealer"
"46":"mcy", #mcy: motorcycles/scooters - by owner"
"47":"mob", #mob: cell phones - by owner"
"48":"mod", #mod: cell phones - by dealer"
"49":"mpo", #mpo: motorcycle parts - by owner"
"50":"msd", #msd: musical instruments - by dealer"
"51":"msg", #msg: musical instruments - by owner"
"52":"phd", #phd: photo/video - by dealer"
"53":"pho", #pho: photo/video - by owner"
"54":"ppd", #ppd: appliances by dealer"
"55":"ptd", #ptd: auto parts by dealer"
"56":"pts", #pts: auto parts by owner"
"57":"rvs", #rvs: rvs by owner"
"58":"sdp", #sdp: computer parts by dealer"
"59":"sgd", #sgd: sporting goods - by dealer"
"60":"snd", #snd: atvs, utvs, snowmobiles - by dealer"
"61":"snw", #snw: atvs, utvs, snowmobiles - by owner"
"62":"sop", #sop: computer parts by owner"
"63":"spo", #spo: sporting good by owner"
"64":"syd", #syd: computers - by dealer"
"65":"sys", #sys: computers - by owner"
"66":"tad", #tad: toys & games - by dealer"
"67":"tag", #tag: toys and games by owner"
"68":"tix", #tix: tix by owner"
"69":"tld", #tld: tools - by dealer"
"70":"tls", #tls: tools - by owner"
"71":"tro", #tro: trailers - by owner"
"72":"vgd", #vgd: video gaming - by dealer"
"73":"vgm", #vgm: video gaming by owner"
"74":"wad", #wad: wanted - by dealer"
"75":"wan", #wan: wanted by owner"
"76":"wtd", #wtd: auto wheels & tires - by dealer"
"77":"wto", #wto: auto wheels & tires - by owner"
"78":"zip"}  #zip: free stuff"